---
- name: Install required packages (client)
  package:
    name: "{{ item }}"
    state: present
  become: true
  when: configure_cockpit|bool
  with_items: "{{ required_packages_cockpit }}"

- name: Setup cockpit server
  include: server.yml
  when:
    - configure_cockpit_server|bool
    - cockpit_groupname_server in group_names
